### PR TITLE
Apply the latest code styling

### PR DESCRIPTION
**Pull request by pranasziaukas**
Change-type: patch
Signed-off-by: Pranas Ziaukas <pranas@balena.io>

### CODE REVIEW

**Comment by AlidaOdendaal** [comment]
@balena-ci rebase

**Comment by pranasziaukas** [comment]
@AlidaOdendaal, FYI, as I understand, either #58 or #64 bump broke the test suite and our CI failed to catch it. I raised it in [this](https://www.flowdock.com/app/rulemotion/d-build-pipelines/threads/2R7u_J1NXSmzrDVuPPf0dSi_5Pb) thread.
Looks like we'll need to rollback to get into the working state.

**Comment by AlidaOdendaal** [comment]
I see, thanks @pranasziaukas , I was just trying to figure out why it's failing...

**Comment by pranasziaukas** [comment]
Yeah. My impression is that some of the function signatures changed between versions. Normally that wouldn't be a problem, but `balena-bulldozer` was not waiting for all of the checks to go green therefore instoducing the broken state along the way.

**Comment by AlidaOdendaal** [comment]
@balena-ci rebase

**Comment by AlidaOdendaal** [comment]
@balena-ci rebase

**Review by AlidaOdendaal — APPROVED** [review]

**Pull request merged**
