### PR TITLE
Remove Matt from the list of devOps

### PR DESCRIPTION
**Pull request by pranasziaukas**
No longer with the company

### CODE REVIEW

**Comment by AlidaOdendaal** [comment]
@balena-ci rebase

**Comment by pranasziaukas** [comment]
I think bumping the dependencies might've surfaced some issues, like a slightly different code styling in a newer version of balena-lint. Trying to address this in #65.

**Comment by AlidaOdendaal** [comment]
@balena-ci rebase

**Comment by AlidaOdendaal** [comment]
@balena-ci rebase

**Comment by AlidaOdendaal** [comment]
@balena-ci rebase

**Review by AlidaOdendaal — APPROVED** [review]

**Pull request merged**
