### PR TITLE
Configure Dependabot

### PR DESCRIPTION
**Pull request by pranasziaukas**
Change-type: minor
Connects-to: #44
Signed-off-by: Pranas Ziaukas <pranas@balena.io>

### CODE REVIEW

**Comment by gelbal** [comment]
Feel free to self-certify this @pranasziaukas. 

I don't know much about `dependabot`, then in the GitHub examples I see that the location of the file is under `.github` directory: https://github.com/dependabot/dependabot-script
Perhaps we might prefer that for the sake of being tidy as we already have that directory in this repo.

Then, I see that JF folks switched to using Renovate in their repos: https://github.com/renovatebot/renovate
Is it worth checking with them why? 
Maybe we'd prefer to stick to using the same tech across balena repos.

**Comment by pranasziaukas** [comment]
Good points @gelbal.

The configuration might've been misplaced so I put it inside `.github`.

Regarding Dependabot v Renovate, I somewhat questioned how the tool was introduced in the first place in the linked issue.
The speculation was that Dependabot is now available as a Github-native bot so including it might be as easy as clicking a checkbox.

Ultimately, I was not the one to include Dependabot here but merely making simple changes to make it work :)
Maybe @Page- has an opinion since he did a ton of work in this repo recently.

**Comment by pranasziaukas** [comment]
@balena-ci rebase

**Comment by pranasziaukas** [comment]
I don't want to dwell on this too much. I'd say we either disable Dependabot altogether or merge the fix.

Given that there were no other opinions and the fix is already prepared I'll give myself liberty to self-certify.

**Comment by pranasziaukas** [comment]
@balena-ci I self-certify!

**Pull request merged**
